bcc-code/bmm-app

- README.md
I added some easy getting started steps which should cover most of the setup needed.
> Add getting started steps

- BMM.Tests/BMM.UITests/BMM.UITests.csproj
- BMM.Tests/BMM.UITests/Views/AlbumPage.cs
- BMM.Tests/BMM.UITests/Views/NavigationBar.cs
- BMM.Tests/BMM.UITests/packages.config
- BMM.UI.iOS/BMM.UI.iOS.csproj
- BMM.UI.iOS/packages.config
Update the UI test to work with the new UI. I had also to update the test packages to be able to run it locally.
> Feature/28250 update UI tests

- BMM.Core/ValueConverters/OfflineAvailableTrackValueConverter.cs
- BMM.Tests/BMM.UITests/AppInitializer.cs
- BMM.Tests/BMM.UITests/BMM.UITests.csproj
- BMM.Tests/BMM.UITests/PodcastPagetests.cs
- BMM.Tests/BMM.UITests/SettingsTests.cs
- BMM.Tests/BMM.UITests/Views/AlbumPage.cs
- BMM.Tests/BMM.UITests/Views/PodcastPage.cs
- BMM.Tests/BMM.UITests/packages.config
- BMM.UI.Android/BMM.UI.Droid.csproj
- BMM.UI.Android/Resources/layout/listitem_tracklist_header.xml
- BMM.UI.iOS/Application/TableViewCell/TrackTableViewCell.cs
- BMM.UI.iOS/Application/TableViewCell/TrackTableViewCell.xib
- BMM.UI.iOS/Application/ViewController/AlbumViewController.xib
- BMM.UI.iOS/Application/ViewController/PodcastViewController.xib
- Adjust the UI tests to the new layout
- Adds additional tests which verifies that downloading the first three songs is still working after following a podcast
> Update UI tests

- BMM.Api.Test/BMM.Api.Test.csproj
- BMM.Api/BMM.Api.csproj
- BMM.Core/BMM.Core.csproj
- BMM.Core/Implementations/Podcasts/PodcastOfflineTrackProvider.cs
- BMM.Core/Implementations/Security/AuthenticatedHttpImageClientHandler.cs
- BMM.UI.Android/Application/Activities/MainActivity.cs
- BMM.UI.Android/Application/Implementations/ViewModelAwareViewPresenter.cs
- BMM.UI.Android/BMM.UI.Droid.csproj
- BMM.UI.iOS/Application/Implementations/Download/IosDownloadDelegate.cs
- BMM.UI.iOS/Application/Implementations/Download/OngoingDownloadsLockDictionary.cs
- BMM.UI.iOS/Application/Implementations/Presenter.cs
- BMM.UI.iOS/BMM.UI.iOS.csproj
- BMM.UI.iOS/packages.config
- Fixes some null reference exceptions
- Remove offline stored podcasts when they are no longer published
- Prevents spamming the logs when images fail to load via FFImageLoading
- Upgrades AndroidX packages
- Upgrades Akavache and Newtonsoft.Json which might bring some small performance improvements
- Use R8 instead fo multiplexing for debug builds as well
> Bug fixes and performance improvements

- BMM.Api/Implementation/Models/BaseTrackCollection.cs
- BMM.Api/Implementation/Models/TrackCollectionReference.cs
- BMM.Core/ViewModels/Base/BaseViewModel.cs
In future the api will no longer accept the access property.
> Remove access from track collection model

- BMM.Core/GuardedActions/Base/BaseGuardedAction.cs
- BMM.Core/ViewModels/SettingsViewModel.cs
We should wait for the results of the build before we merge: https://dev.azure.com/bcc-its/BMM/_build/results?buildId=32548&view=results
> revert using new initializer

- BMM.Core/App.cs
- BMM.Core/Diagnostic/Interfaces/ITimeDiagnosticTool.cs
- BMM.Core/Diagnostic/TimeDiagnosticTool.cs
- BMM.Core/Implementations/Analytics/Event.cs
- BMM.Core/ViewModels/PlaybackHistoryViewModel.cs
- BMM.UI.Android/Application/Fragments/BaseFragment.cs
- BMM.UI.Android/Application/Fragments/PlayerFragment.cs
- Playback history icon disappearing fix
- Logging about empty player view on Android
Closes #76 
Closes #77
> Playback history icon disappearing fix

- BMM.Core/AppNavigator.cs
- BMM.Core/AppStart.cs
- BMM.Core/Implementations/Caching/ICache.cs
- BMM.Core/Implementations/Caching/LocalStorageCache.cs
- BMM.Core/Implementations/PlayObserver/Storage/TrackPlayedStorage.cs
- BMM.Core/Models/Storage/CurrentTrackPositionStorage.cs
- BMM.UI.iOS/Application/NewMediaPlayer/AVAudioPlayback.cs
- BMM.UI.iOS/Application/NewMediaPlayer/IAudioPlayback.cs
- BMM.UI.iOS/Application/NewMediaPlayer/IosMediaPlayer.cs
> Prevent autoplay on queue recovered && TrackPlayedStorage error fix

- BMM.Api.Test/app.config
- BMM.Core/ViewModels/AlbumViewModel.cs
- BMM.Core/ViewModels/Base/BaseViewModel.cs
- BMM.Core/ViewModels/SettingsViewModel.cs
- BMM.Tests/BMM.Core.Test/app.config
- BMM.Tests/BMM.UITests/AutoFollowFromKareTest.cs
- BMM.Tests/BMM.UITests/LibraryArchiveTests.cs
- BMM.Tests/BMM.UITests/PodcastPagetests.cs
- BMM.Tests/BMM.UITests/SettingsTests.cs
- BMM.Tests/BMM.UITests/Views/ExplorePage.cs
- BMM.Tests/BMM.UITests/Views/Menu.cs
- BMM.Tests/BMM.UITests/app.config
- BMM.UI.iOS/Application/ViewController/ExploreNewestViewController.xib
- BMM.UI.iOS/Framework/Base/BaseViewController.cs
> UI Tests fixed

- BMM.UI.iOS/Application/ViewController/PlayerNavigationController.cs
> Transparent header when opening full player view fixed

- BMM.Core/App.cs
- BMM.Core/AppNavigator.cs
- BMM.Core/Helpers/IDeepLinkHandler.cs
- BMM.Core/Implementations/DeepLinking/DeepLinkHandler.cs
- BMM.Core/Implementations/Notifications/INotificationHandler.cs
- BMM.Core/Implementations/Notifications/NotificationHandler.cs
- BMM.Core/Implementations/Player/Interfaces/IRememberedQueueInfoService.cs
- BMM.Core/Implementations/Player/RememberedQueueInfoService.cs
- BMM.UI.Android/Application/Activities/MainActivity.cs
- BMM.UI.iOS/Application/AppDelegate.cs
> Prevent IllegalSeekPositionException when clicking on Track deep link

- BMM.UI.Android/Application/Activities/MainActivity.cs
> Fix deep link handling when app is open

- BMM.Core/Translation/en/main.json
@akrol95 I changed the wording of the settings a bit. What do you think of it?
> change wording of dark mode settings

- BMM.UI.iOS/Application/TableViewCell/Base/BaseBMMTableViewCell.cs
- BMM.UI.iOS/Application/TableViewCell/Base/BaseTrackTableViewCell.cs
- BMM.UI.iOS/Application/TableViewCell/TrackTableViewCell.cs
- BMM.UI.iOS/Application/TableViewSource/PodcastNewestTrackTableViewSource.cs
- BMM.UI.iOS/Application/ViewController/PlayerViewController.cs
> White background on Fra Kaare podcast fix

- BMM.Core/App.cs
- BMM.Core/AppNavigator.cs
- BMM.Core/GuardedActions/App/Interfaces/IOnStartAction.cs
- BMM.Core/Implementations/Analytics/Event.cs
- BMM.Core/Translation/en/Translations.designer.cs
- BMM.Core/Translation/en/main.json
- BMM.Core/ViewModels/ExploreNewestViewModel.cs
- BMM.UI.Android/Application/Actions/OnStartAction.cs
- BMM.UI.Android/Application/Fragments/ExploreNewestFragment.cs
- BMM.UI.Android/Application/Helpers/ISdkVersionHelper.cs
- BMM.UI.Android/Application/Helpers/SdkVersionHelper.cs
- BMM.UI.Android/BMM.UI.Droid.csproj
- BMM.UI.iOS/Application/Actions/OnStartAction.cs
- BMM.UI.iOS/BMM.UI.iOS.csproj
> Background Activity restriction info message

- BMM.Core/GuardedActions/Player/UpdateExternalRelationsAction.cs
- BMM.UI.iOS/Application/CustomViews/DownloadButton.cs
- BMM.UI.iOS/Application/ViewController/CuratedPlaylistViewController.cs
- BMM.UI.iOS/Application/ViewController/TrackCollectionViewController.cs
- BMM.sln.DotSettings
> Lyrics button shown also for "Sangtekst"

- BMM.Core/Implementations/Analytics/Event.cs
- BMM.Core/Implementations/Downloading/DownloadQueue/DownloadQueue.cs
- BMM.Core/Implementations/Downloading/GlobalTrackProvider.cs
- BMM.Core/Implementations/PlaylistPersistence/PlaylistOfflineTrackProvider.cs
- BMM.Core/Utils/ThrottlingDispatcher.cs
- BMM.Core/ViewModels/PlayerBaseViewModel.cs
- BMM.UI.Android/Resources/drawable/seekbar_thumb.xml
- BMM.UI.Android/Resources/layout/fragment_player.axml
- BMM.UI.Android/Resources/values-v21/styles.xml
- BMM.UI.iOS/Application/CustomViews/BmmSliderView.cs
- BMM.UI.iOS/Application/ViewController/PlayerViewController.cs
- BMM.UI.iOS/Application/ViewController/PlayerViewController.designer.cs
- BMM.UI.iOS/Application/ViewController/PlayerViewController.xib
- BMM.UI.iOS/BMM.UI.iOS.csproj
- BMM.UI.iOS/Utils/ImageUtils.cs
Closes #119 
Closes #157  
Closes #162
> Playlist downloading 404 issue fixes + UX imporvements around player progress slider

- BMM.Core/Implementations/Connection/ConnectionStatusLogger.cs
- BMM.Core/Translation/en/Translations.designer.cs
- BMM.Core/Translation/en/main.json
- BMM.Core/ViewModels/Base/DownloadViewModel.cs
- BMM.Core/ViewModels/MyContent/MyTracksViewModel.cs
- BMM.Core/ViewModels/PodcastViewModel.cs
- BMM.Core/ViewModels/SettingsViewModel.cs
- BMM.Tests/BMM.Core.Test/Unit/ViewModels/SettingsViewModelTests.cs
> Download queue when not on Wi-Fi

- BMM.Api/Framework/ILogger.cs
- BMM.Core/Extensions/DictionaryExtensions.cs
- BMM.Core/Implementations/Analytics/AppCenterAnalytics.cs
- BMM.Core/Implementations/Exceptions/ErrorDialogDisplayingLogger.cs
- BMM.Core/Implementations/Exceptions/ExceptionHandler.cs
- BMM.Core/Implementations/FirebaseRemoteConfig/FirebaseRemoteConfig.cs
- BMM.Core/Implementations/FirebaseRemoteConfig/IFirebaseRemoteConfig.cs
- BMM.Core/Implementations/PlayObserver/PlayStatistics.cs
- BMM.Tests/BMM.Core.Test/Unit/Implementations/TrackCollections/AddToTrackCollectionTests.cs
- BMM.UI.Android/AndroidSetup.cs
- BMM.UI.Android/Application/Implementations/AndroidLogger.cs
- BMM.UI.iOS/Application/Implementations/IosSetup.cs
- BMM.UI.iOS/Application/Implementations/iOSLogger.cs
> Logging improvements

- BMM.Core/Implementations/FirebaseRemoteConfig/IPlatformSpecificRemoteConfig.cs
- BMM.UI.Android/Application/Implementations/FirebaseRemoteConfig/AndroidFirebaseRemoteConfig.cs
- BMM.UI.Android/Application/Implementations/Notifications/FirebaseTokenProvider.cs
- BMM.UI.Android/Application/NewMediaPlayer/Notification/CustomAction.cs
- BMM.UI.Android/Application/NewMediaPlayer/Notification/NowPlayingNotificationBuilder.cs
- BMM.UI.Android/Application/NewMediaPlayer/Service/MusicService.cs
- BMM.UI.Android/BMM.UI.Droid.csproj
- BMM.UI.Android/Utils/PendingIntentsUtils.cs
> Android PendingIntent Immutable or Mutable flag needed issue fix

- BMM.Core/Constants/NumericConstants.cs
- BMM.Core/Helpers/ListHelper.cs
- BMM.UI.Android/Application/NewMediaPlayer/Service/MusicService.cs
- BMM.UI.iOS/Application/NewMediaPlayer/AVAudioPlayback.cs
- BMM.UI.iOS/Application/NewMediaPlayer/AVPlayerItemFactory.cs
- BMM.UI.iOS/Application/NewMediaPlayer/AvAudioPlaybackBase.cs
- BMM.UI.iOS/Application/NewMediaPlayer/BMMPlayerItem.cs
- BMM.UI.iOS/Application/NewMediaPlayer/IAudioPlayback.cs
- BMM.UI.iOS/Application/NewMediaPlayer/IosMediaPlayer.cs
- BMM.UI.iOS/BMM.UI.iOS.csproj
> Pre-downloading next song

- BMM.UI.Android/Application/Implementations/Notifications/NotificationDisplayer.cs
> Notification displayer crash fix

- BMM.Core/Implementations/Downloading/DownloadQueue/DownloadQueue.cs
- BMM.UI.iOS/Application/Implementations/IosSetup.cs
> Prevent showing background download errors to users

- BMM.Core/Implementations/Logger/BaseLogger.cs
- BMM.Core/NewMediaPlayer/PlayerErrorHandler.cs
- BMM.UI.Android/Application/Implementations/AndroidLogger.cs
- BMM.UI.iOS/Application/Implementations/iOSLogger.cs
> Sending Warn to Analytics + logger refactor

- BMM.Core/App.cs
- BMM.Core/AppNavigator.cs
- BMM.Core/ViewModels/MiniPlayerViewModel.cs
- BMM.Core/ViewModels/PlayerBaseViewModel.cs
- BMM.Core/ViewModels/PlayerViewModel.cs
- BMM.UI.Android/AndroidSetup.cs
- BMM.UI.Android/Application/Actions/HandleDeepLinkAction.cs
- BMM.UI.Android/Application/Actions/HandleNotificationAction.cs
- BMM.UI.Android/Application/Actions/Interfaces/IHandleDeepLinkAction.cs
- BMM.UI.Android/Application/Actions/Interfaces/IHandleNotificationAction.cs
- BMM.UI.Android/Application/Activities/MainActivity.cs
- BMM.UI.Android/Application/Fragments/PlayerFragment.cs
- BMM.UI.Android/Application/NewMediaPlayer/Controller/AndroidMediaPlayer.cs
- BMM.UI.Android/BMM.UI.Droid.csproj
- BMM.UI.Android/Resources/values/styles.xml
- BMM.UI.Android/SplashScreenActivity.cs
- BMM.UI.iOS/Application/NewMediaPlayer/AVPlayerItemRepository.cs
- BMM.UI.iOS/Application/NewMediaPlayer/CachePlayerItem/CacheMediaFileHandle.cs
- BMM.UI.iOS/Framework/Base/BaseViewController.cs
> Set sizes crash fix

- BMM.Api/Abstraction/ITrackMetadata.cs
- BMM.Api/Implementation/Models/Track.cs
- BMM.Core/App.cs
- BMM.Core/Extensions/MessengerExtensions.cs
- BMM.Core/GuardedActions/ContinueListening/Interfaces/IPlayOrResumePlayAction.cs
- BMM.Core/GuardedActions/ContinueListening/PlayOrResumePlayAction.cs
- BMM.Core/GuardedActions/Documents/PostprocessDocumentsAction.cs
- BMM.Core/Implementations/Factories/ContinueListening/ContinueListeningTilePOFactory.cs
- BMM.Core/Implementations/Factories/Tracks/TrackPOFactory.cs
- BMM.Core/Implementations/Notifications/PodcastNotificationReceiver.cs
- BMM.Core/Models/POs/Base/ITrackHolderPO.cs
- BMM.Core/Models/POs/ContinueListening/ContinueListeningCollectionPO.cs
- BMM.Core/Models/POs/ContinueListening/ContinueListeningTilePO.cs
- BMM.Core/Models/POs/Tracks/TrackPO.cs
- BMM.Core/ViewModels/AlbumViewModel.cs
- BMM.Core/ViewModels/Base/DocumentsViewModel.cs
- BMM.Core/ViewModels/Base/DownloadViewModel.cs
- BMM.Core/ViewModels/ExploreNewestViewModel.cs
- BMM.Core/ViewModels/MyContent/MyContentViewModel.cs
- BMM.Core/ViewModels/PlayerBaseViewModel.cs
- BMM.Core/ViewModels/PlayerViewModel.cs
- BMM.Core/ViewModels/TrackCollectionViewModel.cs
- BMM.Tests/BMM.Core.Test/Unit/GuardedActions/Documents/PostprocessDocumentsActionTests.cs
- BMM.Tests/BMM.Core.Test/Unit/ViewModels/AlbumViewModelTests.cs
- BMM.UI.Android/Resources/layout/listitem_continue_listening.xml
- BMM.UI.iOS/Application/CollectionTableViewCell/ContinueListeningCollectionViewCell.cs
- BMM.UI.iOS/Application/NewMediaPlayer/CachePlayerItem/CacheAVPlayerItemLoader.cs
- BMM.UI.iOS/Application/ViewController/AlbumViewController.cs
- BMM.UI.iOS/Application/ViewController/AlbumViewController.designer.cs
- BMM.UI.iOS/Application/ViewController/AlbumViewController.xib
Suggestion:
ViewModels, which implement ITrackListViewModel are very messy, and views linked to them even more. It would be nice to enclose it in some PO object and refactor all views.
> Post refactor bugs fixes

- BMM.UI.iOS/Application/Implementations/Presenter.cs
- BMM.UI.iOS/Info.plist
> iOS: Sometimes PageSheet cannot be opened fix

- azure-pipelines-android.yaml
> Android Azure Pool changed to local machine

- BMM.Tests/BMM.UITests/BMM.UITests.csproj
- BMM.Tests/BMM.UITests/ExplorePageTests.cs
- BMM.Tests/BMM.UITests/SettingsTests.cs
- BMM.Tests/BMM.UITests/packages.config
- azure-pipelines-android.yaml
> UI Tests fixes

- BMM.Core/AppNavigator.cs
- BMM.Core/Helpers/PresentationHints/CloseTabBarHint.cs
- BMM.Core/Implementations/Security/Oidc/OidcAuthService.cs
- BMM.UI.iOS/Application/Implementations/Presenter.cs
- BMM.UI.iOS/Application/ViewController/MenuViewController.cs
> Login loop issue fix

- BMM.Core/Implementations/ApiClients/ClientCache.cs
- BMM.Core/Implementations/Player/ViewModelHandlingMediaPlayerDecorator.cs
- BMM.Core/NewMediaPlayer/Abstractions/IMediaPlayer.cs
- BMM.UI.Android/Application/NewMediaPlayer/Controller/AndroidMediaPlayer.cs
- BMM.UI.iOS/Application/NewMediaPlayer/IosMediaPlayer.cs
> Changes to shuffle + max cache time set to 1 month

- BMM.Core/ViewModels/Interfaces/ICollectionViewModel.cs
- BMM.Core/ViewModels/SearchResultsViewModel.cs
- BMM.Core/ViewModels/SearchViewModel.cs
- BMM.UI.Android/Resources/layout/fragment_search_results.axml
- BMM.UI.iOS/Application/CollectionTableViewCell/ControllerCollectionViewCell.cs
- BMM.UI.iOS/Application/CollectionViewSource/TopBarCollectionViewSource.cs
- BMM.UI.iOS/Application/TableViewSource/LoadMoreTableViewSource.cs
- BMM.UI.iOS/Application/ViewController/Base/ViewPagerBaseController.cs
- BMM.UI.iOS/Application/ViewController/SearchResultsViewController.cs
> Search fixes

- BMM.Core/Implementations/Analytics/Event.cs
- BMM.Core/Implementations/UI/BaseUriOpener.cs
- BMM.UI.Android/Application/Implementations/UI/UriOpener.cs
- BMM.UI.iOS/Application/Implementations/UI/UriOpener.cs
> Logging click on external link

- BMM.Api/Implementation/Clients/Contracts/IContributorClient.cs
- BMM.Api/Implementation/Clients/ContributorClient.cs
- BMM.Core/Implementations/ApiClients/CachedContributorClientDecorator.cs
- BMM.Core/Implementations/Caching/CacheKeys.cs
- BMM.Core/ViewModels/ExploreContributorsViewModel.cs
- BMM.Tests/BMM.Core.Test/Unit/ViewModels/ExploreContributorsViewModelTests.cs
- BMM.UI.iOS/Application/ViewController/ExploreContributorsViewController.cs
> 'Explore Contributors' - load data form the API

- BMM.Core/Implementations/PlayObserver/PersistingPlayStatisticsDecorator.cs
- BMM.Core/Implementations/Player/ViewModelHandlingMediaPlayerDecorator.cs
- BMM.UI.iOS/BMM.UI.iOS.csproj
iOS .csproj updated according to: https://github.com/xamarin/xamarin-macios/wiki/Project-file-properties
> Problem with saving modified queue fixed

- BMM.Core/ViewModels/ContributorViewModel.cs
- BMM.UI.Android/Application/Activities/MainActivity.cs
- BMM.UI.Android/Application/Fragments/PlayerFragment.cs
- BMM.UI.Android/Application/Implementations/DroidUserDialogs.cs
- BMM.UI.Android/Application/Implementations/UI/DroidUserDialogsFactory.cs
- BMM.UI.Android/Application/NewMediaPlayer/Controller/AndroidMediaPlayer.cs
- BMM.UI.iOS/Application/Actions/PlayMusicFromSiriAction.cs
- BMM.UI.iOS/Application/NewMediaPlayer/AVAudioPlayback.cs
- BMM.UI.iOS/Application/NewMediaPlayer/AvAudioPlaybackBase.cs
- BMM.UI.iOS/Application/NewMediaPlayer/CachePlayerItem/CacheMediaFileHandle.cs
- BMM.UI.iOS/Application/TableViewSource/Base/BaseTableViewSource.cs
- BMM.UI.iOS/BMM.UI.iOS.csproj
- BMM.UI.iOS/Framework/Base/BaseViewController.cs
> Crash fixes

- BMM.Core/Models/POs/BibleStudy/AchievementPO.cs
- BMM.Core/Utils/AchievementsTools.cs
- BMM.Core/ViewModels/Base/DocumentsViewModel.cs
- BMM.Core/ViewModels/QueueViewModel.cs
- BMM.UI.Android/Application/Fragments/SharedTrackCollectionFragment.cs
- BMM.UI.Android/Application/NewMediaPlayer/Playback/ExoPlaybackPreparer.cs
- BMM.UI.Android/Resources/drawable/highlighted_text_play_button_background.xml
Closes #477 
Closes #478 
Closes #479
> Cumulative fixes

- BMM.Core/Implementations/Connection/AkavacheBlobSettingsStorage.cs
- BMM.Core/Implementations/Connection/ISettingsStorage.cs
- BMM.Core/Implementations/FirebaseRemoteConfig/FirebaseRemoteConfig.cs
- BMM.Core/Implementations/FirebaseRemoteConfig/IFirebaseRemoteConfig.cs
- BMM.Core/Implementations/Storage/AppSettings.cs
- BMM.Core/Translation/en/Translations.designer.cs
- BMM.Core/Translation/en/main.json
- BMM.Core/ViewModels/PodcastViewModel.cs
- BMM.Core/ViewModels/SettingsViewModel.cs
- BMM.Tests/BMM.Core.Test/Unit/ViewModels/PodcastViewModelTests.cs
- BMM.UI.iOS/Application/TableViewCell/ListItem/CheckboxListItemTableViewCell.xib
- BMM.UI.iOS/Application/TableViewCell/ListItem/TextListItemDetailTableViewCell.xib
- BMM.UI.iOS/Application/TableViewSource/SettingsTableViewSource.cs
- BMM.UI.iOS/Application/ViewController/SettingsViewController.xib
#570 
+ fix for cut off description labels in Settings on iOS
> Play Podcast in chronological order

- BMM.UI.iOS/Application/AppDelegate.cs
- BMM.UI.iOS/Application/BmmWindowSceneDelegate.cs
> Deep links fixes

- BMM.Api/Framework/JsonConverter/JsonCreationConverter.cs
> Cache fixes

- BMM.Core/Translation/ro/main.json
> New Phrase Updates
